services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    #Twig\Extensions\IntlExtension: ~
    Twig\Extensions\TextExtension: ~

#        twig.extension.text:
#        class: Twig_Extensions_Extension_Text
#            tags:
#                - { name: twig.extension }
