
# Below is the full default configuration for the bundle:
# https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/configuration_reference.md
# The reference can be dumped using the following command: php bin/console debug:config vich_uploader

vich_uploader:

    db_driver: orm

    mappings:

        news:
            uri_prefix: /images/news
#            upload_destination: '%kernel.project_dir%/public/images/news'
            upload_destination: '%env(PUBLIC_ROOT)%/images/news'
#            delete_on_remove: true
#            delete_on_update: true
            namer: vich_uploader.namer_uniqid

        courses:
            uri_prefix: /images/courses
            upload_destination: '%env(PUBLIC_ROOT)%/images/courses'
            namer: vich_uploader.namer_uniqid

        lectures:
            uri_prefix: /images/lectures
            upload_destination: '%env(PUBLIC_ROOT)%/images/lectures'
            namer: vich_uploader.namer_uniqid
